version: '3'
services:
  app:
    image: redwonder/jailgas-rails:latest
    container_name: rails
    volumes:
      - ./log/app:/var/www/jailgas/log
  web:
    image: redwonder/jailgas-nginx:latest
    container_name: nginx
    volumes:
      - ./log/web:/var/www/jailgas/log
    ports:
      - "80:80"
    depends_on:
      - app

